---SITE

MERGE INTO "B4B85072923A44789F391B1E8CB24202"."TELCEL_EE_SITE" AS SITE
USING (
SELECT 
	(SUBSTR(LOWER(TO_NVARCHAR(SYSUUID)), 1, 8) || '-' ||
    LPAD(TO_NVARCHAR(CEIL(RAND() * 65535)), 4, '0') || '-' ||
    LPAD(TO_NVARCHAR(CEIL(RAND() * 4095)), 4, '0') || '-' ||
    LPAD(TO_NVARCHAR(CEIL(RAND() * 4095)), 4, '0') || '-' ||
    LPAD(TO_NVARCHAR(CEIL(RAND() * 4095)), 4, '0') ||
    LPAD(TO_NVARCHAR(CEIL(RAND() * 4095)), 4, '0') ||
    LPAD(TO_NVARCHAR(CEIL(RAND() * 4095)), 4, '0')) AS ID,
    CREATEDAT AS CREATEDAT,
	'anonymous' AS CREATEDBY,
	CREATEDAT AS MODIFIEDAT,
	'privileged' AS MODIFIEDBY,
	NAME AS NAME,
	(SUBSTR(LOWER(TO_NVARCHAR(SYSUUID)), 1, 8) || '-' ||
    LPAD(TO_NVARCHAR(CEIL(RAND() * 65535)), 4, '0') || '-' ||
    LPAD(TO_NVARCHAR(CEIL(RAND() * 4095)), 4, '0') || '-' ||
    LPAD(TO_NVARCHAR(CEIL(RAND() * 4095)), 4, '0') || '-' ||
    LPAD(TO_NVARCHAR(CEIL(RAND() * 4095)), 4, '0') ||
    LPAD(TO_NVARCHAR(CEIL(RAND() * 4095)), 4, '0') ||
    LPAD(TO_NVARCHAR(CEIL(RAND() * 4095)), 4, '0')) AS ADDRESSID,
	'e0fb2418-5484-4735-83fd-64fac0399503' AS COMPANYID, 
	SITETYPE AS SITETYPE,
	'' AS BUSINESSUNIT,
	REGION AS REGION,
	LEFT(EXTERNALID, 6) AS EXTERNALID,
	COSTCENTER AS COSTCENTER,
	LPAD(RPU,12,'0') AS RPU,
	UPPER(DIVISION) AS DIVISION,
	LPAD(TRIM(SUBSTRING(FARE, INSTR(FARE, '(') + 1, INSTR(FARE, ')') - INSTR(FARE, '(') - 1)),2,'0') AS FARE,
	'' AS FORMAT,
	'' AS TIMEZONE,
    '' AS OPENHOUR,
    '' AS CLOSEHOUR,
    '' AS CONTACT,
    '' AS CONTACTPHONE,
    '' AS CONTACTEMAIL,
	'' AS AUTHUSER,
	'' AS ELECTRICSUPPLIER,
	'' AS GASSUPPLIER,
	'' AS WATERSUPPLIER,
	(SUBSTR(LOWER(TO_NVARCHAR(SYSUUID)), 1, 8) || '-' ||
    LPAD(TO_NVARCHAR(CEIL(RAND() * 65535)), 4, '0') || '-' ||
    LPAD(TO_NVARCHAR(CEIL(RAND() * 4095)), 4, '0') || '-' ||
    LPAD(TO_NVARCHAR(CEIL(RAND() * 4095)), 4, '0') || '-' ||
    LPAD(TO_NVARCHAR(CEIL(RAND() * 4095)), 4, '0') ||
    LPAD(TO_NVARCHAR(CEIL(RAND() * 4095)), 4, '0') ||
    LPAD(TO_NVARCHAR(CEIL(RAND() * 4095)), 4, '0')) AS GATEWAYID,
	(SUBSTR(LOWER(TO_NVARCHAR(SYSUUID)), 1, 8) || '-' ||
    LPAD(TO_NVARCHAR(CEIL(RAND() * 65535)), 4, '0') || '-' ||
    LPAD(TO_NVARCHAR(CEIL(RAND() * 4095)), 4, '0') || '-' ||
    LPAD(TO_NVARCHAR(CEIL(RAND() * 4095)), 4, '0') || '-' ||
    LPAD(TO_NVARCHAR(CEIL(RAND() * 4095)), 4, '0') ||
    LPAD(TO_NVARCHAR(CEIL(RAND() * 4095)), 4, '0') ||
    LPAD(TO_NVARCHAR(CEIL(RAND() * 4095)), 4, '0')) AS SIMID,
	'' AS STATUS,    /*SOLICITAR INFO*/
	0 AS DELETIONREQUEST,
	CONTRACTEDDEMAND AS CONTRACTEDDEMAND,
	'' AS CUTOFFDATE,
	'' AS COSTCENTEREG,
	0 AS MULTIPLIER,
	'' AS MANAGER,
	METER AS METER,
	ACCOUNT AS ACCOUNT,
	COMPANYDIVISION AS COMPANYDIVISION,
	ADDRESSCFE AS ADDRESSCFE,
	SAPACCOUNT AS SAPACCOUNT,
	'' AS SUPPLIER,
	FOLIO1 AS FOLIO1,
	FOLIO2 AS FOLIO2,
	CORPORATION AS CORPORATION,
	RFCCORPORATION AS RFCCORPORATION, /*AGREGAR*/
	ADDRESSTELCEL AS ADDRESSTELCEL,   /*AGREGAR*/
	TRIM(SUBSTRING(FARE, 1, INSTR(FARE, '(') - 1)) AS FAREACTUAL /*AGREGAR*/
   FROM "B4B85072923A44789F391B1E8CB24202"."TELCEL_EE_INITCOBCEN"
) AS COBCEN
ON SITE.RPU = COBCEN.RPU
WHEN MATCHED THEN

	UPDATE SET
        SITE.MODIFIEDAT = COBCEN.MODIFIEDAT,
        SITE.MODIFIEDBY = COBCEN.MODIFIEDBY,
        SITE.NAME = COBCEN.NAME,
        SITE.SITETYPE = COBCEN.SITETYPE,
        SITE.REGION = COBCEN.REGION,
        SITE.EXTERNALID = COBCEN.EXTERNALID,
        SITE.COSTCENTER = COBCEN.COSTCENTER,
        SITE.DIVISION = COBCEN.DIVISION,
        SITE.FARE = COBCEN.FARE,
        SITE.CONTRACTEDDEMAND = COBCEN.CONTRACTEDDEMAND,
		SITE.METER = COBCEN.METER,
		SITE.ACCOUNT = COBCEN.ACCOUNT,
		SITE.COMPANYDIVISION = COBCEN.COMPANYDIVISION,
		SITE.ADDRESSCFE = COBCEN.ADDRESSCFE,
		SITE.SAPACCOUNT = COBCEN.SAPACCOUNT,
		SITE.SUPPLIER = COBCEN.SUPPLIER,
		SITE.FOLIO1 = COBCEN.FOLIO1,
		SITE.FOLIO2 = COBCEN.FOLIO2,
		SITE.CORPORATION = COBCEN.CORPORATION

WHEN NOT MATCHED THEN
	INSERT
    (ID, CREATEDAT, CREATEDBY, MODIFIEDAT, MODIFIEDBY, NAME, ADDRESSID, COMPANYID, SITETYPE, BUSINESSUNIT, REGION, EXTERNALID, COSTCENTER, RPU, 
    DIVISION, FARE, FORMAT, TIMEZONE, OPENHOUR, CLOSEHOUR, CONTACT, CONTACTPHONE, CONTACTEMAIL, AUTHUSER, ELECTRICSUPPLIER, GASSUPPLIER, WATERSUPPLIER, 
    GATEWAYID, SIMID, STATUS, DELETIONREQUEST, CONTRACTEDDEMAND, CUTOFFDATE, COSTCENTEREG, MULTIPLIER, MANAGER, METER, ACCOUNT, COMPANYDIVISION, ADDRESSCFE, 
    SAPACCOUNT, SUPPLIER, FOLIO1, FOLIO2, CORPORATION)
    VALUES(COBCEN.ID, COBCEN.CREATEDAT, COBCEN.CREATEDBY, COBCEN.MODIFIEDAT, COBCEN.MODIFIEDBY, COBCEN.NAME, COBCEN.ADDRESSID, COBCEN.COMPANYID, COBCEN.SITETYPE, 
    COBCEN.BUSINESSUNIT, COBCEN.REGION, COBCEN.EXTERNALID, COBCEN.COSTCENTER, COBCEN.RPU, COBCEN.DIVISION, COBCEN.FARE, COBCEN.FORMAT, COBCEN.TIMEZONE, COBCEN.OPENHOUR,
    COBCEN.CLOSEHOUR, COBCEN.CONTACT, COBCEN.CONTACTPHONE, COBCEN.CONTACTEMAIL, COBCEN.AUTHUSER, COBCEN.ELECTRICSUPPLIER, COBCEN.GASSUPPLIER, COBCEN.WATERSUPPLIER, 
    COBCEN.GATEWAYID, COBCEN.SIMID, COBCEN.STATUS, COBCEN.DELETIONREQUEST, COBCEN.CONTRACTEDDEMAND, COBCEN.CUTOFFDATE, COBCEN.COSTCENTEREG, COBCEN.MULTIPLIER, 
    COBCEN.MANAGER, COBCEN.METER, COBCEN.ACCOUNT, COBCEN.COMPANYDIVISION, COBCEN.ADDRESSCFE, COBCEN.SAPACCOUNT, COBCEN.SUPPLIER, COBCEN.FOLIO1, COBCEN.FOLIO2, COBCEN.CORPORATION);
   
---ADDRESS  
   
MERGE INTO "B4B85072923A44789F391B1E8CB24202"."TELCEL_EE_ADDRESS" AS ADDRESS
USING (
SELECT 
	ST.ADDRESSID AS ID,
	ST.CREATEDAT AS CREATEDAT,
	ST.CREATEDBY AS CREATEDBY,
	ST.MODIFIEDAT AS MODIFIEDAT,
	ST.MODIFIEDBY AS MODIFIEDBY,
	'' AS ADDRESSTYPE,
	'' AS COUNTRY,
	CB.STATE AS STATE,
	CB.TOWN AS TOWN,
	CB.POSTALCODE AS POSTALCODE,
	'' AS NEIGHBORHOOD,
	CB.ADDRESSTELCEL AS STREET,
	'' AS EXTNUMBER,
	'' AS INTNUMBER,
	0 AS LATITUDE,
	0 AS LONGITUDE,
	0 AS BUILTAREA
	FROM "B4B85072923A44789F391B1E8CB24202"."TELCEL_EE_INITCOBCEN" AS CB
	INNER JOIN "B4B85072923A44789F391B1E8CB24202"."TELCEL_EE_SITE" AS ST
	ON CB.RPU = ST.RPU
) AS COBCEN	
ON ADDRESS.ID = COBCEN.ID  
WHEN MATCHED THEN

	UPDATE SET
		ADDRESS.MODIFIEDAT = COBCEN.MODIFIEDAT,
		ADDRESS.MODIFIEDBY = COBCEN.MODIFIEDBY,
        ADDRESS.TOWN = COBCEN.TOWN,
        ADDRESS.STATE = COBCEN.STATE,
        ADDRESS.POSTALCODE = COBCEN.POSTALCODE
        
WHEN NOT MATCHED THEN
	INSERT
	(ID, CREATEDAT, CREATEDBY, MODIFIEDAT, MODIFIEDBY, ADDRESSTYPE, COUNTRY, STATE, TOWN, POSTALCODE, NEIGHBORHOOD, STREET, EXTNUMBER, INTNUMBER, LATITUDE, LONGITUDE, BUILTAREA) 
	VALUES(COBCEN.ID, COBCEN.CREATEDAT, COBCEN.CREATEDBY, COBCEN.MODIFIEDAT, COBCEN.MODIFIEDBY, COBCEN.ADDRESSTYPE, COBCEN.COUNTRY, COBCEN.STATE, COBCEN.TOWN, 
    COBCEN.POSTALCODE, COBCEN.NEIGHBORHOOD, COBCEN.STREET, COBCEN.EXTNUMBER, COBCEN.INTNUMBER, COBCEN.LATITUDE, COBCEN.LONGITUDE, COBCEN.BUILTAREA);


---GATEWAY  
   
MERGE INTO "B4B85072923A44789F391B1E8CB24202"."TELCEL_EE_GATEWAY" AS GATEWAY
USING (
SELECT 
	ST.GATEWAYID AS ID,
	ST.CREATEDAT AS CREATEDAT,
	ST.CREATEDBY AS CREATEDBY,
	ST.MODIFIEDAT AS MODIFIEDAT,
	ST.MODIFIEDBY AS MODIFIEDBY,
	'' AS NAME,
	'' AS SERIALNUMBER,
	'' AS PIN
	FROM "B4B85072923A44789F391B1E8CB24202"."TELCEL_EE_INITCOBCEN" AS CB
	INNER JOIN "B4B85072923A44789F391B1E8CB24202"."TELCEL_EE_SITE" AS ST
	ON CB.RPU = ST.RPU
) AS COBCEN	
ON GATEWAY.ID = COBCEN.ID  
WHEN MATCHED THEN

	UPDATE SET
		GATEWAY.MODIFIEDAT = COBCEN.MODIFIEDAT,
		GATEWAY.MODIFIEDBY = COBCEN.MODIFIEDBY,
        GATEWAY.NAME = COBCEN.NAME,
        GATEWAY.SERIALNUMBER = COBCEN.SERIALNUMBER,
        GATEWAY.PIN = COBCEN.PIN

WHEN NOT MATCHED THEN
	INSERT
	(ID, CREATEDAT, CREATEDBY, MODIFIEDAT, MODIFIEDBY, NAME, SERIALNUMBER, PIN) 
	VALUES(COBCEN.ID, COBCEN.CREATEDAT, COBCEN.CREATEDBY, COBCEN.MODIFIEDAT, COBCEN.MODIFIEDBY, COBCEN.NAME, COBCEN.SERIALNUMBER, COBCEN.PIN);


---SIM  
   
MERGE INTO "B4B85072923A44789F391B1E8CB24202"."TELCEL_EE_SIM" AS SIM
USING (
SELECT 
	ST.SIMID AS ID,
	ST.CREATEDAT AS CREATEDAT,
	ST.CREATEDBY AS CREATEDBY,
	ST.MODIFIEDAT AS MODIFIEDAT,
	ST.MODIFIEDBY AS MODIFIEDBY,
	'' AS MSASDN,
	'' AS IMSI
	FROM "B4B85072923A44789F391B1E8CB24202"."TELCEL_EE_INITCOBCEN" AS CB
	INNER JOIN "B4B85072923A44789F391B1E8CB24202"."TELCEL_EE_SITE" AS ST
	ON CB.RPU = ST.RPU
) AS COBCEN	
ON SIM.ID = COBCEN.ID  
WHEN MATCHED THEN

	UPDATE SET
		SIM.MODIFIEDAT = COBCEN.MODIFIEDAT,
		SIM.MODIFIEDBY = COBCEN.MODIFIEDBY,
        SIM.MSASDN = COBCEN.MSASDN,
        SIM.IMSI = COBCEN.IMSI

WHEN NOT MATCHED THEN
	INSERT
	(ID, CREATEDAT, CREATEDBY, MODIFIEDAT, MODIFIEDBY, MSASDN, IMSI) 
	VALUES(COBCEN.ID, COBCEN.CREATEDAT, COBCEN.CREATEDBY, COBCEN.MODIFIEDAT, COBCEN.MODIFIEDBY, COBCEN.MSASDN, COBCEN.IMSI);