MERGE INTO B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPHUAWEICOUNTERS AS principal
USING (
    SELECT DISTINCT
        t1.TIME,
        SUBSTRING(t1.NODEBNAME, 1, 6) AS NODEBNAME,
        t1.NODEBNAME AS IDBTSNAME,
        t1.VSCELLDYNSHUTDOWN AS VSCELLDYNSHUTDOWN
    FROM B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPWCDMAHUAWEICOUNTERS AS t1
    WHERE DELTA IS NULL
) AS datosActualizados1
ON principal.FECHA = datosActualizados1."TIME"
AND principal.BTSNAME = datosActualizados1.NODEBNAME
AND principal.IDBTSNAME = datosActualizados1.IDBTSNAME
WHEN MATCHED THEN
    UPDATE SET
        principal.VSCELLDYNSHUTDOWN = COALESCE(datosActualizados1.VSCELLDYNSHUTDOWN, principal.VSCELLDYNSHUTDOWN)
WHEN NOT MATCHED THEN
    INSERT
    (FECHA, BTSNAME, IDBTSNAME, VSCELLDYNSHUTDOWN)
    VALUES(datosActualizados1."TIME", datosActualizados1.NODEBNAME, datosActualizados1.IDBTSNAME, datosActualizados1.VSCELLDYNSHUTDOWN);
 
-- UPDATE B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPWCDMAHUAWEICOUNTERS
-- SET DELTA = 1;

 

UPDATE B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPLTEDFEEHUAWEICOUNTERS
SET LCHMEASDFEECARRIERDYNMUTINGTTI = 0
WHERE LCHMEASDFEECARRIERDYNMUTINGTTI IS NULL;
 
UPDATE B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPLTEDFEEHUAWEICOUNTERS
SET LCHMEASDFEECARRIEROFF = 0
WHERE LCHMEASDFEECARRIEROFF IS NULL;
 
UPDATE B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPLTEDFEEHUAWEICOUNTERS
SET LCHMEASDFEEOPPRFOFF = 0
WHERE LCHMEASDFEEOPPRFOFF IS NULL;
 
UPDATE B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPLTEDFEEHUAWEICOUNTERS
SET LCHMEASDFEERFOFF = 0
WHERE LCHMEASDFEERFOFF IS NULL;
 
UPDATE B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPLTEDFEEHUAWEICOUNTERS
SET LCHMEASDFEEPROACTIVESCHTTI = 0
WHERE LCHMEASDFEEPROACTIVESCHTTI IS NULL;
 

MERGE INTO B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPHUAWEICOUNTERS AS principal
USING (
    SELECT DISTINCT
        t1.TIME,
        SUBSTRING(t1.NODEBNAME, 1, 6) AS NODEBNAME,
        t1.NODEBNAME AS IDBTSNAME,
        CAST(t1.LCHMEASDFEECARRIERDYNMUTINGTTI AS DECIMAL) AS LCHMEASDFEECARRIERDYNMUTINGTTI,
        CAST(t1.LCHMEASDFEECARRIEROFF AS DECIMAL) AS LCHMEASDFEECARRIEROFF,
        CAST(t1.LCHMEASDFEEOPPRFOFF AS DECIMAL) AS LCHMEASDFEEOPPRFOFF,
        CAST(t1.LCHMEASDFEERFOFF AS DECIMAL) AS LCHMEASDFEERFOFF
    FROM B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPLTEDFEEHUAWEICOUNTERS AS t1
    WHERE DELTA IS NULL
    ORDER BY NODEBNAME, TIME
) AS datosActualizados1
ON principal.FECHA = datosActualizados1."TIME"
AND principal.BTSNAME = datosActualizados1.NODEBNAME
AND principal.IDBTSNAME = datosActualizados1.IDBTSNAME
WHEN MATCHED THEN
    UPDATE SET
        principal.LCHMEASDFEECARRIERDYNMUTINGTTI = COALESCE(datosActualizados1.LCHMEASDFEECARRIERDYNMUTINGTTI, principal.LCHMEASDFEECARRIERDYNMUTINGTTI),
        principal.LCHMEASDFEECARRIEROFF = COALESCE(datosActualizados1.LCHMEASDFEECARRIEROFF, principal.LCHMEASDFEECARRIEROFF),
        principal.LCHMEASDFEEOPPRFOFF = COALESCE(datosActualizados1.LCHMEASDFEEOPPRFOFF, principal.LCHMEASDFEEOPPRFOFF),
        principal.LCHMEASDFEERFOFF = COALESCE(datosActualizados1.LCHMEASDFEERFOFF, principal.LCHMEASDFEERFOFF)
WHEN NOT MATCHED THEN
    INSERT
    (FECHA, BTSNAME, IDBTSNAME, LCHMEASDFEECARRIERDYNMUTINGTTI, LCHMEASDFEECARRIEROFF, LCHMEASDFEEOPPRFOFF, LCHMEASDFEERFOFF)
    VALUES(datosActualizados1."TIME", datosActualizados1.NODEBNAME, datosActualizados1.IDBTSNAME,
    datosActualizados1.LCHMEASDFEECARRIERDYNMUTINGTTI,
    datosActualizados1.LCHMEASDFEECARRIEROFF,
    datosActualizados1.LCHMEASDFEEOPPRFOFF,
    datosActualizados1.LCHMEASDFEERFOFF
    );
 
-- UPDATE B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPLTEDFEEHUAWEICOUNTERS
-- SET DELTA = 1;
 
 


UPDATE B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPLTENODEHUAWEICOUNTERS
SET VSENERGYADDINGGSM2G = '0'
WHERE VSENERGYADDINGGSM2G = 'NIL';
 
UPDATE B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPLTENODEHUAWEICOUNTERS
SET VSENERGYADDINGUMTS3G = '0'
WHERE VSENERGYADDINGUMTS3G = 'NIL';
 
UPDATE B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPLTENODEHUAWEICOUNTERS
SET VSENERGYADDINGLTE4G = '0'
WHERE VSENERGYADDINGLTE4G = 'NIL';
 
UPDATE B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPLTENODEHUAWEICOUNTERS
SET VSENERGYADDINGR5G = '0'
WHERE VSENERGYADDINGR5G = 'NIL';
 
 


MERGE INTO B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPHUAWEICOUNTERS AS principal
USING (
    SELECT * FROM (
        SELECT 
            t1.TIME,
            SUBSTRING(t1.NODEBNAME, 1, 6) AS NODEBNAME,
            t1.NODEBNAME AS IDBTSNAME, 
            CAST(t1.VSENERGYADDINGGSM2G AS DECIMAL) AS VSENERGYGSM2G,
            CAST(t1.VSENERGYADDINGUMTS3G AS DECIMAL) AS VSENERGYUMTS3G,
            CAST(t1.VSENERGYADDINGLTE4G AS DECIMAL) AS VSENERGYLTE4G,
            CAST(t1.VSENERGYADDINGR5G AS DECIMAL) AS VSENERGYNR5G,
            ROW_NUMBER() OVER (
                PARTITION BY TIME, SUBSTRING(t1.NODEBNAME, 1, 6), t1.NODEBNAME  
                ORDER BY TIME
            ) AS rn
        FROM B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPLTENODEHUAWEICOUNTERS AS t1
        WHERE DELTA IS NULL
    ) WHERE rn = 1
) AS datosActualizados1
ON principal.FECHA = datosActualizados1."TIME"
AND principal.BTSNAME = datosActualizados1.NODEBNAME
AND principal.IDBTSNAME = datosActualizados1.IDBTSNAME
WHEN MATCHED THEN
    UPDATE SET
    	principal.VSENERGYGSM2G = COALESCE(datosActualizados1.VSENERGYGSM2G, principal.VSENERGYGSM2G),
        principal.VSENERGYUMTS3G = COALESCE(datosActualizados1.VSENERGYUMTS3G, principal.VSENERGYUMTS3G),
        principal.VSENERGYLTE4G = COALESCE(datosActualizados1.VSENERGYLTE4G, principal.VSENERGYLTE4G),
        principal.VSENERGYNR5G = COALESCE(datosActualizados1.VSENERGYNR5G, principal.VSENERGYNR5G)
WHEN NOT MATCHED THEN
	INSERT
    (FECHA, BTSNAME, IDBTSNAME, VSENERGYGSM2G, VSENERGYUMTS3G, VSENERGYLTE4G, VSENERGYNR5G)
    VALUES(
        datosActualizados1."TIME", 
        datosActualizados1.NODEBNAME, 
        datosActualizados1.IDBTSNAME,
        datosActualizados1.VSENERGYGSM2G,
        datosActualizados1.VSENERGYUMTS3G,
        datosActualizados1.VSENERGYLTE4G,
        datosActualizados1.VSENERGYNR5G
    );
    
-- UPDATE B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPLTENODEHUAWEICOUNTERS
-- SET DELTA = 1;   
 

UPDATE B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMP5GHUAWEICOUNTERS
SET NPOWERSAVINGRFSHUTDOWN = '0'
WHERE NPOWERSAVINGRFSHUTDOWN IS NULL;
 
UPDATE B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMP5GHUAWEICOUNTERS
SET NPOWERSAVINGSYMBOLSHUTDOWN = '0'
WHERE NPOWERSAVINGSYMBOLSHUTDOWN IS NULL;
 


MERGE INTO B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPHUAWEICOUNTERS AS principal
USING (
    SELECT DISTINCT
        t1.TIME,
        SUBSTRING(t1.NODEBNAME, 1, 6) AS NODEBNAME,
        t1.NODEBNAME AS IDBTSNAME,
        CAST(t1.NPOWERSAVINGSYMBOLSHUTDOWN AS DECIMAL) AS NPOWERSAVINGSYMBOLSHUTDOWN,
        CAST(t1.NPOWERSAVINGRFSHUTDOWN AS DECIMAL) AS NPOWERSAVINGRFSHUTDOWN
    FROM B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMP5GHUAWEICOUNTERS AS t1
    WHERE DELTA IS NULL
) AS datosActualizados1
ON principal.FECHA = datosActualizados1."TIME"
AND principal.BTSNAME = datosActualizados1.NODEBNAME
AND principal.IDBTSNAME = datosActualizados1.IDBTSNAME
WHEN MATCHED THEN
    UPDATE SET
        principal.NPOWERSAVINGSYMBOLSHUTDOWN = COALESCE(datosActualizados1.NPOWERSAVINGSYMBOLSHUTDOWN, principal.NPOWERSAVINGSYMBOLSHUTDOWN),
        principal.NPOWERSAVINGRFSHUTDOWN = COALESCE(datosActualizados1.NPOWERSAVINGRFSHUTDOWN, principal.NPOWERSAVINGRFSHUTDOWN)
WHEN NOT MATCHED THEN
    INSERT
    (FECHA, BTSNAME, IDBTSNAME, NPOWERSAVINGSYMBOLSHUTDOWN, NPOWERSAVINGRFSHUTDOWN)
    VALUES(datosActualizados1."TIME", datosActualizados1.NODEBNAME, datosActualizados1.IDBTSNAME,
    datosActualizados1.NPOWERSAVINGSYMBOLSHUTDOWN, datosActualizados1.NPOWERSAVINGRFSHUTDOWN);
    
-- UPDATE B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMP5GHUAWEICOUNTERS
-- SET DELTA = 1;