--5G EnergyMeter Ericsson------------------------------------
UPSERT B4B85072923A44789F391B1E8CB24202.TELCEL_EE_ENERGYMETERERICSSON5G
SELECT "TIME", NODEBNAME, "HOUR", CONSUMEDENERGY, CONSUMEDENERGYACCUMULATED, MINPOWERCONSUMPTION, VOLTAGE, PROVEEDOR, TECNOLOGIA, 1 AS DELTA, 
       LPAD(MONTH(TO_DATE("TIME", 'MON DD YYYY')), 2, '0') || '.' || YEAR(TO_DATE("TIME", 'MON DD YYYY')) AS ANIOMES
FROM B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPENERGYMETERERICSSON5G;

SELECT TO_VARCHAR(TO_DATE("TIME", 'MON DD YYYY'), 'YYYY-MM-DD') AS FECHA,
       TO_VARCHAR(LPAD(TO_VARCHAR("HOUR"), 2, '0')) || ':00:00' AS HORA,
       SUBSTRING(TRIM(NODEBNAME), 1, 6) AS BTSNAME,
       TRIM(NODEBNAME) AS IDBTSNAME,
	   CASE 
        WHEN CONSUMEDENERGY IS NULL OR TRIM(BOTH ' ' FROM CONSUMEDENERGY) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM CONSUMEDENERGY) AS DECIMAL)
       END AS CONSUMEDENERGY,
	   CASE 
        WHEN CONSUMEDENERGYACCUMULATED IS NULL OR TRIM(BOTH ' ' FROM CONSUMEDENERGYACCUMULATED) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM CONSUMEDENERGYACCUMULATED) AS DECIMAL)
       END AS CONSUMEDENERGYACCUMULATED,
	   CASE 
        WHEN VOLTAGE IS NULL OR TRIM(BOTH ' ' FROM VOLTAGE) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM VOLTAGE) AS DECIMAL)
      END AS VOLTAGE,
	   0 AS POWERCONSUMPTION,
	   CASE 
        WHEN MINPOWERCONSUMPTION IS NULL OR TRIM(BOTH ' ' FROM MINPOWERCONSUMPTION) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM MINPOWERCONSUMPTION) AS DECIMAL)
      END AS MINPOWERCONSUMPTION,
	   0 AS MAXPOWERCONSUMPTION,
	   0 AS MIMOSLEEPOPPTIME,
	   0 AS MIMOSLEEPTIME, 
	   0 AS CELLSLEEPFAILUECAP,
	   0 AS CELLSLEEPTIME, PROVEEDOR, TECNOLOGIA,
       'EnergyMeter' AS OBJECTTYPE
FROM B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPENERGYMETERERICSSON5G
INTO B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPERICSSONCOUNTERS;

TRUNCATE TABLE B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPENERGYMETERERICSSON5G;

--5G EnergyConsumed Ericsson------------------------------------
UPSERT B4B85072923A44789F391B1E8CB24202.TELCEL_EE_ENERGYCONSUMEDERICSSON5G
SELECT "TIME", NODEBNAME, "HOUR", CONSUMEDENERGY, CONSUMEDENERGYACCUMULATED, MINPOWERCONSUMPTION, VOLTAGE, PROVEEDOR, TECNOLOGIA, 1 AS DELTA, 
       LPAD(MONTH(TO_DATE("TIME", 'MON DD YYYY')), 2, '0') || '.' || YEAR(TO_DATE("TIME", 'MON DD YYYY')) AS ANIOMES
FROM B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPENERGYCONSUMEDERICSSON5G;

SELECT TO_VARCHAR(TO_DATE("TIME", 'MON DD YYYY'), 'YYYY-MM-DD') AS FECHA,
       TO_VARCHAR(LPAD(TO_VARCHAR("HOUR"), 2, '0')) || ':00:00' AS HORA,
       SUBSTRING(TRIM(NODEBNAME), 1, 6) AS BTSNAME,
       TRIM(NODEBNAME) AS IDBTSNAME,
	   CASE 
        WHEN CONSUMEDENERGY IS NULL OR TRIM(BOTH ' ' FROM CONSUMEDENERGY) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM CONSUMEDENERGY) AS DECIMAL)
       END AS CONSUMEDENERGY,
	   CASE 
        WHEN CONSUMEDENERGYACCUMULATED IS NULL OR TRIM(BOTH ' ' FROM CONSUMEDENERGYACCUMULATED) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM CONSUMEDENERGYACCUMULATED) AS DECIMAL)
       END AS CONSUMEDENERGYACCUMULATED,
	   CASE 
        WHEN VOLTAGE IS NULL OR TRIM(BOTH ' ' FROM VOLTAGE) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM VOLTAGE) AS DECIMAL)
      END AS VOLTAGE,
	   0 AS POWERCONSUMPTION,
	   CASE 
        WHEN MINPOWERCONSUMPTION IS NULL OR TRIM(BOTH ' ' FROM MINPOWERCONSUMPTION) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM MINPOWERCONSUMPTION) AS DECIMAL)
      END AS MINPOWERCONSUMPTION,
	   0 AS MAXPOWERCONSUMPTION,
	   0 AS MIMOSLEEPOPPTIME,
	   0 AS MIMOSLEEPTIME, 
	   0 AS CELLSLEEPFAILUECAP,
	   0 AS CELLSLEEPTIME, PROVEEDOR, TECNOLOGIA,
       'ConsumedEnergyMeasurement' AS OBJECTTYPE
FROM B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPENERGYCONSUMEDERICSSON5G
INTO B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPERICSSONCOUNTERS;

TRUNCATE TABLE B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPENERGYCONSUMEDERICSSON5G;

--BB Consumed Energy Measurement------------------------------------
UPSERT B4B85072923A44789F391B1E8CB24202.TELCEL_EE_BBCONSUMEDENERGYMEASUREMENTERICSSON
SELECT "TIME", NODEBNAME, "HOUR", CONSUMEDENERGY, CONSUMEDENERGYACCUMULATED, POWERCONSUMPTION, VOLTAGE, PROVEEDOR, TECNOLOGIA, 1 AS DELTA, 
       LPAD(MONTH(TO_DATE("TIME", 'MON DD YYYY')), 2, '0') || '.' || YEAR(TO_DATE("TIME", 'MON DD YYYY')) AS ANIOMES
FROM B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPBBCONSUMEDENERGYMEASUREMENTERICSSON;

SELECT 
    TO_VARCHAR(TO_DATE("TIME", 'MON DD YYYY'), 'YYYY-MM-DD') AS FECHA,
    TO_VARCHAR(LPAD(TO_VARCHAR("HOUR"), 2, '0')) || ':00:00' AS HORA,
    SUBSTRING(TRIM(NODEBNAME), 1, 6) AS BTSNAME,
    TRIM(NODEBNAME) AS IDBTSNAME,
    CASE 
        WHEN CONSUMEDENERGY IS NULL OR TRIM(BOTH ' ' FROM CONSUMEDENERGY) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM CONSUMEDENERGY) AS DECIMAL)
       END AS CONSUMEDENERGY,
	   CASE 
        WHEN CONSUMEDENERGYACCUMULATED IS NULL OR TRIM(BOTH ' ' FROM CONSUMEDENERGYACCUMULATED) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM CONSUMEDENERGYACCUMULATED) AS DECIMAL)
       END AS CONSUMEDENERGYACCUMULATED,
    CASE 
        WHEN VOLTAGE IS NULL OR TRIM(BOTH ' ' FROM VOLTAGE) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM VOLTAGE) AS DECIMAL)
    END AS VOLTAGE,
    CASE 
        WHEN POWERCONSUMPTION IS NULL OR TRIM(BOTH ' ' FROM POWERCONSUMPTION) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM POWERCONSUMPTION) AS DECIMAL)
    END AS POWERCONSUMPTION,
    0 AS MINPOWERCONSUMPTION,
	0 AS MAXPOWERCONSUMPTION,
	0 AS MIMOSLEEPOPPTIME,
	0 AS MIMOSLEEPTIME, 
	0 AS CELLSLEEPFAILUECAP,
	0 AS CELLSLEEPTIME, PROVEEDOR, TECNOLOGIA,
    'ConsumedEnergyMeasurement' AS OBJECTTYPE
FROM B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPBBCONSUMEDENERGYMEASUREMENTERICSSON
WHERE TRIM(NODEBNAME) NOT LIKE '%NR'
INTO B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPERICSSONCOUNTERS;

TRUNCATE TABLE B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPBBCONSUMEDENERGYMEASUREMENTERICSSON;

--BB Energy Meter------------------------------------
UPSERT B4B85072923A44789F391B1E8CB24202.TELCEL_EE_BBENERGYMETERERICSSON
SELECT "TIME", NODEBNAME, "HOUR", CONSUMEDENERGY, CONSUMEDENERGYACCUMULATED, MAXPOWERCONSUMPTION, MINPOWERRCONSUMPTION, VOLTAGE, PROVEEDOR, TECNOLOGIA, 1 AS DELTA, 
       LPAD(MONTH(TO_DATE("TIME", 'MON DD YYYY')), 2, '0') || '.' || YEAR(TO_DATE("TIME", 'MON DD YYYY')) AS ANIOMES
FROM B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPBBENERGYMETERERICSSON;

SELECT TO_VARCHAR(TO_DATE("TIME", 'MON DD YYYY'), 'YYYY-MM-DD') AS FECHA,
       TO_VARCHAR(LPAD(TO_VARCHAR("HOUR"), 2, '0')) || ':00:00' AS HORA,
       SUBSTRING(TRIM(NODEBNAME), 1, 6) AS BTSNAME,
       TRIM(NODEBNAME) AS IDBTSNAME,
	   CASE 
        WHEN CONSUMEDENERGY IS NULL OR TRIM(BOTH ' ' FROM CONSUMEDENERGY) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM CONSUMEDENERGY) AS DECIMAL)
       END AS CONSUMEDENERGY,
	   CASE 
        WHEN CONSUMEDENERGYACCUMULATED IS NULL OR TRIM(BOTH ' ' FROM CONSUMEDENERGYACCUMULATED) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM CONSUMEDENERGYACCUMULATED) AS DECIMAL)
       END AS CONSUMEDENERGYACCUMULATED,
	   CASE 
        WHEN VOLTAGE IS NULL OR TRIM(BOTH ' ' FROM VOLTAGE) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM VOLTAGE) AS DECIMAL)
       END AS VOLTAGE,
	   0 AS POWERCONSUMPTION,
	   CASE 
        WHEN MINPOWERRCONSUMPTION IS NULL OR TRIM(BOTH ' ' FROM MINPOWERRCONSUMPTION) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM MINPOWERRCONSUMPTION) AS DECIMAL)
       END AS MINPOWERCONSUMPTION,
       CASE 
        WHEN MAXPOWERCONSUMPTION IS NULL OR TRIM(BOTH ' ' FROM MAXPOWERCONSUMPTION) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM MAXPOWERCONSUMPTION) AS DECIMAL)
       END AS MAXPOWERCONSUMPTION,
       0 AS MIMOSLEEPOPPTIME,
	   0 AS MIMOSLEEPTIME, 
	   0 AS CELLSLEEPFAILUECAP,
	   0 AS CELLSLEEPTIME,
	   PROVEEDOR, TECNOLOGIA,
       'EnergyMeter' AS OBJECTTYPE
FROM B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPBBENERGYMETERERICSSON
WHERE TRIM(NODEBNAME) NOT LIKE '%NR'
INTO B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPERICSSONCOUNTERS;

TRUNCATE TABLE B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPBBENERGYMETERERICSSON;

--DU Consumed Energy Measurement------------------------------------
UPSERT B4B85072923A44789F391B1E8CB24202.TELCEL_EE_DUCONSUMEDENERGYMEASUREMENTERICSSON
SELECT "TIME", NODEBNAME, "HOUR", CONSUMEDENERGY, CONSUMEDENERGYACCUMULATED, POWERCONSUMPTION, VOLTAGE, PROVEEDOR, TECNOLOGIA, 1 AS DELTA, 
       LPAD(MONTH(TO_DATE("TIME", 'MON DD YYYY')), 2, '0') || '.' || YEAR(TO_DATE("TIME", 'MON DD YYYY')) AS ANIOMES
FROM B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPDUCONSUMEDENERGYMEASUREMENTERICSSON;

SELECT TO_VARCHAR(TO_DATE("TIME", 'MON DD YYYY'), 'YYYY-MM-DD') AS FECHA,
       TO_VARCHAR(LPAD(TO_VARCHAR("HOUR"), 2, '0')) || ':00:00' AS HORA,
       SUBSTRING(TRIM(NODEBNAME), 1, 6) AS BTSNAME,
       TRIM(NODEBNAME) AS IDBTSNAME,
       CASE 
        WHEN CONSUMEDENERGY IS NULL OR TRIM(BOTH ' ' FROM CONSUMEDENERGY) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM CONSUMEDENERGY) AS DECIMAL)
       END AS CONSUMEDENERGY,
	   CASE 
        WHEN CONSUMEDENERGYACCUMULATED IS NULL OR TRIM(BOTH ' ' FROM CONSUMEDENERGYACCUMULATED) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM CONSUMEDENERGYACCUMULATED) AS DECIMAL)
       END AS CONSUMEDENERGYACCUMULATED,
	   CASE 
        WHEN VOLTAGE IS NULL OR TRIM(BOTH ' ' FROM VOLTAGE) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM VOLTAGE) AS DECIMAL)
       END AS VOLTAGE,
       CASE 
        WHEN POWERCONSUMPTION IS NULL OR TRIM(BOTH ' ' FROM POWERCONSUMPTION) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM POWERCONSUMPTION) AS DECIMAL)
       END AS POWERCONSUMPTION,
	   0 AS MINPOWERCONSUMPTION,
	   0 AS MAXPOWERCONSUMPTION,
	   0 AS MIMOSLEEPOPPTIME,
	   0 AS MIMOSLEEPTIME, 
	   0 AS CELLSLEEPFAILUECAP,
	   0 AS CELLSLEEPTIME, PROVEEDOR, TECNOLOGIA,
       'ConsumedEnergyMeasurement' AS OBJECTTYPE
FROM B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPDUCONSUMEDENERGYMEASUREMENTERICSSON
WHERE TRIM(NODEBNAME) NOT LIKE '%NR'
INTO B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPERICSSONCOUNTERS;

TRUNCATE TABLE B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPDUCONSUMEDENERGYMEASUREMENTERICSSON;

--DU Energy Meter------------------------------------
UPSERT B4B85072923A44789F391B1E8CB24202.TELCEL_EE_DUENERGYMETERERICSSON
SELECT "TIME", NODEBNAME, "HOUR", CONSUMEDENERGY, CONSUMEDENERGYACCUMULATED, POWERCONSUMPTION, VOLTAGE, PROVEEDOR, TECNOLOGIA, 1 AS DELTA, 
       LPAD(MONTH(TO_DATE("TIME", 'MON DD YYYY')), 2, '0') || '.' || YEAR(TO_DATE("TIME", 'MON DD YYYY')) AS ANIOMES
FROM B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPDUENERGYMETERERICSSON;

SELECT TO_VARCHAR(TO_DATE("TIME", 'MON DD YYYY'), 'YYYY-MM-DD') AS FECHA,
       TO_VARCHAR(LPAD(TO_VARCHAR("HOUR"), 2, '0')) || ':00:00' AS HORA,
       SUBSTRING(TRIM(NODEBNAME), 1, 6) AS BTSNAME,
       TRIM(NODEBNAME) AS IDBTSNAME,
	   CASE 
        WHEN CONSUMEDENERGY IS NULL OR TRIM(BOTH ' ' FROM CONSUMEDENERGY) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM CONSUMEDENERGY) AS DECIMAL)
       END AS CONSUMEDENERGY,
	   CASE 
        WHEN CONSUMEDENERGYACCUMULATED IS NULL OR TRIM(BOTH ' ' FROM CONSUMEDENERGYACCUMULATED) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM CONSUMEDENERGYACCUMULATED) AS DECIMAL)
       END AS CONSUMEDENERGYACCUMULATED,
       CASE 
        WHEN VOLTAGE IS NULL OR TRIM(BOTH ' ' FROM VOLTAGE) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM VOLTAGE) AS DECIMAL)
       END AS VOLTAGE,
       CASE 
        WHEN POWERCONSUMPTION IS NULL OR TRIM(BOTH ' ' FROM POWERCONSUMPTION) = 'NULL' THEN 0
        ELSE CAST(TRIM(BOTH ' ' FROM POWERCONSUMPTION) AS DECIMAL)
       END AS POWERCONSUMPTION,
	   0 AS MINPOWERCONSUMPTION,
	   0 AS MAXPOWERCONSUMPTION,
	   0 AS MIMOSLEEPOPPTIME,
	   0 AS MIMOSLEEPTIME, 
	   0 AS CELLSLEEPFAILUECAP,
	   0 AS CELLSLEEPTIME, PROVEEDOR, TECNOLOGIA,
       'EnergyMeter' AS OBJECTTYPE
FROM B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPDUENERGYMETERERICSSON
WHERE TRIM(NODEBNAME) NOT LIKE '%NR'
INTO B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPERICSSONCOUNTERS;

TRUNCATE TABLE B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPDUENERGYMETERERICSSON;

--EUTRAN
UPSERT B4B85072923A44789F391B1E8CB24202.TELCEL_EE_EUTRANERICSSON
SELECT "TIME", NODEBNAME, "HOUR", MIMOSLEEPOPPTIME, MIMOSLEEPTIME, CELLSLEEPFAILUECAP, CELLSLEEPTIME, VOLTAGE, PROVEEDOR, TECNOLOGIA, 1 AS DELTA, 
       LPAD(MONTH(TO_DATE("TIME", 'MON DD YYYY')), 2, '0') || '.' || YEAR(TO_DATE("TIME", 'MON DD YYYY')) AS MESANIO
FROM B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPEUTRANERICSSON;

MERGE INTO B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPERICSSONCOUNTERS AS principal
USING (
    SELECT DISTINCT
        TO_VARCHAR(TO_DATE("TIME", 'MON DD YYYY'), 'YYYY-MM-DD') AS FECHA,
        TO_VARCHAR(LPAD(TO_VARCHAR("HOUR"), 2, '0')) || ':00:00' AS HORA,
        SUBSTRING(TRIM(NODEBNAME), 1, 6) AS BTSNAME,
        TRIM(NODEBNAME) AS IDBTSNAME,
        CASE
            WHEN MIMOSLEEPOPPTIME IS NULL OR TRIM(BOTH ' ' FROM MIMOSLEEPOPPTIME) = 'NULL' THEN 0
            ELSE CAST(TRIM(BOTH ' ' FROM MIMOSLEEPOPPTIME) AS DECIMAL)
        END AS MIMOSLEEPOPPTIME,
        CASE
            WHEN MIMOSLEEPTIME IS NULL OR TRIM(BOTH ' ' FROM MIMOSLEEPTIME) = 'NULL' THEN 0
            ELSE CAST(TRIM(BOTH ' ' FROM MIMOSLEEPTIME) AS DECIMAL)
        END AS MIMOSLEEPTIME,
        CASE
            WHEN CELLSLEEPFAILUECAP IS NULL OR TRIM(BOTH ' ' FROM CELLSLEEPFAILUECAP) = 'NULL' THEN 0
            ELSE CAST(TRIM(BOTH ' ' FROM CELLSLEEPFAILUECAP) AS DECIMAL)
        END AS CELLSLEEPFAILUECAP,
        CASE
            WHEN CELLSLEEPTIME IS NULL OR TRIM(BOTH ' ' FROM CELLSLEEPTIME) = 'NULL' THEN 0
            ELSE CAST(TRIM(BOTH ' ' FROM CELLSLEEPTIME) AS DECIMAL)
        END AS CELLSLEEPTIME,
        CASE 
            WHEN VOLTAGE IS NULL OR TRIM(BOTH ' ' FROM VOLTAGE) = 'NULL' THEN 0
            ELSE CAST(TRIM(BOTH ' ' FROM VOLTAGE) AS DECIMAL)
        END AS VOLTAGE,
        PROVEEDOR, TECNOLOGIA,
        'EUtranCellFDD' AS OBJECTTYPE
    FROM B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPEUTRANERICSSON AS t1
) AS datosActualizados1
ON principal.FECHA = datosActualizados1."FECHA"
AND principal.HORA = datosActualizados1."HORA"
AND principal.BTSNAME = datosActualizados1.BTSNAME
AND principal.IDBTSNAME = datosActualizados1.IDBTSNAME
WHEN MATCHED THEN
    UPDATE SET
        principal.MIMOSLEEPOPPTIME = COALESCE(datosActualizados1.MIMOSLEEPOPPTIME, principal.MIMOSLEEPOPPTIME),
        principal.MIMOSLEEPTIME = COALESCE(datosActualizados1.MIMOSLEEPTIME, principal.MIMOSLEEPTIME),
        principal.CELLSLEEPFAILUECAP = COALESCE(datosActualizados1.CELLSLEEPFAILUECAP, principal.CELLSLEEPFAILUECAP),
        principal.CELLSLEEPTIME = COALESCE(datosActualizados1.CELLSLEEPTIME, principal.CELLSLEEPTIME)
WHEN NOT MATCHED THEN
    INSERT
    (FECHA, HORA, BTSNAME, IDBTSNAME, CONSUMEDENERGY, CONSUMEDENERGYACCUMULATED, VOLTAGE, POWERCONSUMPTION, MINPOWERCONSUMPTION, 
    MAXPOWERCONSUMPTION, MIMOSLEEPOPPTIME, MIMOSLEEPTIME, CELLSLEEPFAILUECAP, CELLSLEEPTIME, PROVEEDOR, TECNOLOGIA, OBJECTTYPE)
    VALUES(datosActualizados1.FECHA, datosActualizados1.HORA, datosActualizados1.BTSNAME, datosActualizados1.IDBTSNAME,
    0, 0, 0, 0, 0, 0,
    datosActualizados1.MIMOSLEEPOPPTIME,
    datosActualizados1.MIMOSLEEPTIME,
    datosActualizados1.CELLSLEEPFAILUECAP,
    datosActualizados1.CELLSLEEPTIME,
    datosActualizados1.PROVEEDOR,
    datosActualizados1.TECNOLOGIA,
    datosActualizados1.OBJECTTYPE);
    
TRUNCATE TABLE B4B85072923A44789F391B1E8CB24202.TELCEL_EE_TEMPEUTRANERICSSON;